### PR TITLE
Test parametrized gitlab-runneer version with Ansible

### PR DESCRIPTION
**Pull request by simonemex**

### CODE REVIEW

**Comment by angelbarrera92** [comment]
LGTM

**Comment by lnovara** [comment]
@simonemex @angelbarrera92 should we default to always install the latest version (`gitlab_runner_version: "*"`) or should we pin the current latest?

**Comment by angelbarrera92** [comment]
As @lnovara mention, i prefer set it up the actual latest version in the new `gitlab_runner_version` this way we ensure what version we are installing following the "current" behavior (this is what i think @simonemex is doing) and we fix the version for upcoming releases.

**Comment by lnovara** [comment]
@simonemex can you do the proposed change so that we can merge?

Thank you.

**Comment by simonemex** [comment]
Change made.

The module still need to be tested, if you agree we can wait the test before to merge the PR.

**Comment by angelbarrera92** [comment]
> Change made.
> 
> The module still need to be tested, if you agree we can wait the test before to merge the PR.

What kind of test? Manually? Local Automated (molecule)?

**Comment by simonemex** [comment]
I have in plan to deploy the module on a real environment and according to the result I'll tell you if this change is ok

**Comment by lnovara** [comment]
OK, let us know @simonemex.

**Comment by simonemex** [comment]
Test passed. I made a little correction.

**Comment by lnovara** [comment]
Thank you @simonemex. Merging.

**Pull request merged**
